site :opscode

cookbook 'build-essential'
cookbook 'apt'
cookbook 'mc', :git => 'https://github.com/lunsher/chef-mc'
cookbook 'zsh'
cookbook 'vagrant-zsh', :git => 'https://github.com/avalancheau/cookbook-vagrant-zsh'
cookbook 'oh-my-zsh', :git => 'https://github.com/shingara/oh-my-zsh-chef'
cookbook 'git'
cookbook 'curl'
cookbook 'ntp'
cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'rvm-user', :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'libxml2', :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'imagemagick'
cookbook 'postgresql'
cookbook 'python'